# Generated by Django 2.2.4 on 2019-08-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
            },
        ),
        migrations.CreateModel(
            name='Top100',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.IntegerField()),
                ('title', models.CharField(max_length=255, unique=True)),
                ('stars', models.CharField(max_length=255)),
                ('release_time', models.CharField(max_length=255)),
                ('score', models.FloatField()),
                ('img_url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'top_100',
            },
        ),
    ]
