"""empty message

Revision ID: 722fa714645b
Revises: 0de3b4c3235a
Create Date: 2019-09-29 18:38:40.948382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '722fa714645b'
down_revision = '0de3b4c3235a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
